---
  - name: Install apache2 for Ubuntu
    apt: 
      name: apache2
      state: latest        
    when: ansible_distribution == "Ubuntu"

  - name: Install PHP for Ubuntu
    apt: 
      name: libapache2-mod-php
      state: latest         
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 for CentOS
    yum: 
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install PHP packages for CentOS
    yum: 
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
